load("@build_stack_rules_proto//rules:proto_gazelle.bzl", "proto_gazelle")
load("@build_stack_rules_proto//rules/go:module.bzl", "go_modules", "go_vendor")
load("@gazelle//:def.bzl", "gazelle_binary")

# -- Gazelle language "walk" ---
# gazelle:exclude vendor

# -- Gazelle language "resolve" ---
# gazelle:resolve go go github.com/stackb/rules_proto/pkg/protoc @build_stack_rules_proto//pkg/protoc

# -- Gazelle language "go" ---
# gazelle:prefix github.com/stackb/bazel-aquery-differ
# gazelle:go_generate_proto false

# -- Gazelle language "protobuf" ---

# --- the base configuration in rules_proto_config.yaml is tailored for external protos
# --- such as @bazelapis.  For the default (source) workspace, switch it from
# --- proto_compile to proto_compiled_sources and disable proto_go_library.
# gazelle:proto_language go +rule proto_compiled_sources
# gazelle:proto_language go -rule proto_compile
# gazelle:proto_language go -rule proto_go_library

gazelle_binary(
    name = "gazelle-protobuf",
    languages = [
        "@gazelle//language/proto:go_default_library",
        "@gazelle//language/go:go_default_library",
        "@build_stack_rules_proto//language/protobuf",
        "@build_stack_rules_proto//language/gomodules",
    ],
)

proto_gazelle(
    name = "gazelle",
    cfgs = ["//:rules_proto_config.yaml"],
    command = "update",
    gazelle = ":gazelle-protobuf",
    imports = [
        "@bazelapis//:imports.csv",
        "@googleapis//:imports.csv",
        "@protoapis//:imports.csv",
        "@remoteapis//:imports.csv",
    ],
)

go_vendor(
    name = "go_vendor",
    modules = [
        "@protoapis//google/protobuf:go_module",
    ],
    deps = [
        "//build/stack/bazel/aquery/differ:differ_go_proto",
        "@bazelapis//src/main/protobuf:analysis_v2_go_proto",
        "@bazelapis//src/main/protobuf:build_go_proto",
        # "@protoapis//google/protobuf:any_go_proto",
        # "@protoapis//google/protobuf:descriptor_go_proto",
        # "@protoapis//google/protobuf:struct_go_proto",
        # "@protoapis//google/protobuf:timestamp_go_proto",
    ],
)

go_modules(
    name = "go_modules",
    deps = ["@bazel-aquery-differ//build/stack/bazel/aquery/differ:go_module"],
)
