load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "stardoc_output",
    srcs = ["stardoc_output.pb.go"],
    importpath = "github.com/stackb/bazel-aquery-differ/genproto/github.com/bazelbuild/bazel/src/main/protobuf/stardoc_output",
    visibility = ["//visibility:public"],
    deps = [
        "@org_golang_google_protobuf//reflect/protoreflect:go_default_library",
        "@org_golang_google_protobuf//runtime/protoimpl:go_default_library",
    ],
)
