// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: src/main/protobuf/stardoc_output.proto

package stardoc_output

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttributeType int32

const (
	AttributeType_UNKNOWN           AttributeType = 0
	AttributeType_NAME              AttributeType = 1
	AttributeType_INT               AttributeType = 2
	AttributeType_LABEL             AttributeType = 3
	AttributeType_STRING            AttributeType = 4
	AttributeType_STRING_LIST       AttributeType = 5
	AttributeType_INT_LIST          AttributeType = 6
	AttributeType_LABEL_LIST        AttributeType = 7
	AttributeType_BOOLEAN           AttributeType = 8
	AttributeType_LABEL_STRING_DICT AttributeType = 9
	AttributeType_STRING_DICT       AttributeType = 10
	AttributeType_STRING_LIST_DICT  AttributeType = 11
	AttributeType_OUTPUT            AttributeType = 12
	AttributeType_OUTPUT_LIST       AttributeType = 13
	AttributeType_LABEL_DICT_UNARY  AttributeType = 14
)

// Enum value maps for AttributeType.
var (
	AttributeType_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "NAME",
		2:  "INT",
		3:  "LABEL",
		4:  "STRING",
		5:  "STRING_LIST",
		6:  "INT_LIST",
		7:  "LABEL_LIST",
		8:  "BOOLEAN",
		9:  "LABEL_STRING_DICT",
		10: "STRING_DICT",
		11: "STRING_LIST_DICT",
		12: "OUTPUT",
		13: "OUTPUT_LIST",
		14: "LABEL_DICT_UNARY",
	}
	AttributeType_value = map[string]int32{
		"UNKNOWN":           0,
		"NAME":              1,
		"INT":               2,
		"LABEL":             3,
		"STRING":            4,
		"STRING_LIST":       5,
		"INT_LIST":          6,
		"LABEL_LIST":        7,
		"BOOLEAN":           8,
		"LABEL_STRING_DICT": 9,
		"STRING_DICT":       10,
		"STRING_LIST_DICT":  11,
		"OUTPUT":            12,
		"OUTPUT_LIST":       13,
		"LABEL_DICT_UNARY":  14,
	}
)

func (x AttributeType) Enum() *AttributeType {
	p := new(AttributeType)
	*p = x
	return p
}

func (x AttributeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttributeType) Descriptor() protoreflect.EnumDescriptor {
	return file_src_main_protobuf_stardoc_output_proto_enumTypes[0].Descriptor()
}

func (AttributeType) Type() protoreflect.EnumType {
	return &file_src_main_protobuf_stardoc_output_proto_enumTypes[0]
}

func (x AttributeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttributeType.Descriptor instead.
func (AttributeType) EnumDescriptor() ([]byte, []int) {
	return file_src_main_protobuf_stardoc_output_proto_rawDescGZIP(), []int{0}
}

type FunctionParamRole int32

const (
	FunctionParamRole_PARAM_ROLE_UNSPECIFIED     FunctionParamRole = 0
	FunctionParamRole_PARAM_ROLE_ORDINARY        FunctionParamRole = 1
	FunctionParamRole_PARAM_ROLE_POSITIONAL_ONLY FunctionParamRole = 2
	FunctionParamRole_PARAM_ROLE_KEYWORD_ONLY    FunctionParamRole = 3
	FunctionParamRole_PARAM_ROLE_VARARGS         FunctionParamRole = 4
	FunctionParamRole_PARAM_ROLE_KWARGS          FunctionParamRole = 5
)

// Enum value maps for FunctionParamRole.
var (
	FunctionParamRole_name = map[int32]string{
		0: "PARAM_ROLE_UNSPECIFIED",
		1: "PARAM_ROLE_ORDINARY",
		2: "PARAM_ROLE_POSITIONAL_ONLY",
		3: "PARAM_ROLE_KEYWORD_ONLY",
		4: "PARAM_ROLE_VARARGS",
		5: "PARAM_ROLE_KWARGS",
	}
	FunctionParamRole_value = map[string]int32{
		"PARAM_ROLE_UNSPECIFIED":     0,
		"PARAM_ROLE_ORDINARY":        1,
		"PARAM_ROLE_POSITIONAL_ONLY": 2,
		"PARAM_ROLE_KEYWORD_ONLY":    3,
		"PARAM_ROLE_VARARGS":         4,
		"PARAM_ROLE_KWARGS":          5,
	}
)

func (x FunctionParamRole) Enum() *FunctionParamRole {
	p := new(FunctionParamRole)
	*p = x
	return p
}

func (x FunctionParamRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FunctionParamRole) Descriptor() protoreflect.EnumDescriptor {
	return file_src_main_protobuf_stardoc_output_proto_enumTypes[1].Descriptor()
}

func (FunctionParamRole) Type() protoreflect.EnumType {
	return &file_src_main_protobuf_stardoc_output_proto_enumTypes[1]
}

func (x FunctionParamRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FunctionParamRole.Descriptor instead.
func (FunctionParamRole) EnumDescriptor() ([]byte, []int) {
	return file_src_main_protobuf_stardoc_output_proto_rawDescGZIP(), []int{1}
}

type ModuleInfo struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	RuleInfo            []*RuleInfo             `protobuf:"bytes,1,rep,name=rule_info,json=ruleInfo,proto3" json:"rule_info,omitempty"`
	ProviderInfo        []*ProviderInfo         `protobuf:"bytes,2,rep,name=provider_info,json=providerInfo,proto3" json:"provider_info,omitempty"`
	FuncInfo            []*StarlarkFunctionInfo `protobuf:"bytes,3,rep,name=func_info,json=funcInfo,proto3" json:"func_info,omitempty"`
	AspectInfo          []*AspectInfo           `protobuf:"bytes,4,rep,name=aspect_info,json=aspectInfo,proto3" json:"aspect_info,omitempty"`
	ModuleDocstring     string                  `protobuf:"bytes,5,opt,name=module_docstring,json=moduleDocstring,proto3" json:"module_docstring,omitempty"`
	File                string                  `protobuf:"bytes,6,opt,name=file,proto3" json:"file,omitempty"`
	ModuleExtensionInfo []*ModuleExtensionInfo  `protobuf:"bytes,7,rep,name=module_extension_info,json=moduleExtensionInfo,proto3" json:"module_extension_info,omitempty"`
	RepositoryRuleInfo  []*RepositoryRuleInfo   `protobuf:"bytes,8,rep,name=repository_rule_info,json=repositoryRuleInfo,proto3" json:"repository_rule_info,omitempty"`
	MacroInfo           []*MacroInfo            `protobuf:"bytes,9,rep,name=macro_info,json=macroInfo,proto3" json:"macro_info,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ModuleInfo) Reset() {
	*x = ModuleInfo{}
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleInfo) ProtoMessage() {}

func (x *ModuleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleInfo.ProtoReflect.Descriptor instead.
func (*ModuleInfo) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_stardoc_output_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleInfo) GetRuleInfo() []*RuleInfo {
	if x != nil {
		return x.RuleInfo
	}
	return nil
}

func (x *ModuleInfo) GetProviderInfo() []*ProviderInfo {
	if x != nil {
		return x.ProviderInfo
	}
	return nil
}

func (x *ModuleInfo) GetFuncInfo() []*StarlarkFunctionInfo {
	if x != nil {
		return x.FuncInfo
	}
	return nil
}

func (x *ModuleInfo) GetAspectInfo() []*AspectInfo {
	if x != nil {
		return x.AspectInfo
	}
	return nil
}

func (x *ModuleInfo) GetModuleDocstring() string {
	if x != nil {
		return x.ModuleDocstring
	}
	return ""
}

func (x *ModuleInfo) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *ModuleInfo) GetModuleExtensionInfo() []*ModuleExtensionInfo {
	if x != nil {
		return x.ModuleExtensionInfo
	}
	return nil
}

func (x *ModuleInfo) GetRepositoryRuleInfo() []*RepositoryRuleInfo {
	if x != nil {
		return x.RepositoryRuleInfo
	}
	return nil
}

func (x *ModuleInfo) GetMacroInfo() []*MacroInfo {
	if x != nil {
		return x.MacroInfo
	}
	return nil
}

type RuleInfo struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RuleName            string                 `protobuf:"bytes,1,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	DocString           string                 `protobuf:"bytes,2,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	Attribute           []*AttributeInfo       `protobuf:"bytes,3,rep,name=attribute,proto3" json:"attribute,omitempty"`
	OriginKey           *OriginKey             `protobuf:"bytes,4,opt,name=origin_key,json=originKey,proto3" json:"origin_key,omitempty"`
	AdvertisedProviders *ProviderNameGroup     `protobuf:"bytes,5,opt,name=advertised_providers,json=advertisedProviders,proto3" json:"advertised_providers,omitempty"`
	Test                bool                   `protobuf:"varint,6,opt,name=test,proto3" json:"test,omitempty"`
	Executable          bool                   `protobuf:"varint,7,opt,name=executable,proto3" json:"executable,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RuleInfo) Reset() {
	*x = RuleInfo{}
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleInfo) ProtoMessage() {}

func (x *RuleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleInfo.ProtoReflect.Descriptor instead.
func (*RuleInfo) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_stardoc_output_proto_rawDescGZIP(), []int{1}
}

func (x *RuleInfo) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *RuleInfo) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

func (x *RuleInfo) GetAttribute() []*AttributeInfo {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *RuleInfo) GetOriginKey() *OriginKey {
	if x != nil {
		return x.OriginKey
	}
	return nil
}

func (x *RuleInfo) GetAdvertisedProviders() *ProviderNameGroup {
	if x != nil {
		return x.AdvertisedProviders
	}
	return nil
}

func (x *RuleInfo) GetTest() bool {
	if x != nil {
		return x.Test
	}
	return false
}

func (x *RuleInfo) GetExecutable() bool {
	if x != nil {
		return x.Executable
	}
	return false
}

type MacroInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MacroName     string                 `protobuf:"bytes,1,opt,name=macro_name,json=macroName,proto3" json:"macro_name,omitempty"`
	DocString     string                 `protobuf:"bytes,2,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	Attribute     []*AttributeInfo       `protobuf:"bytes,3,rep,name=attribute,proto3" json:"attribute,omitempty"`
	OriginKey     *OriginKey             `protobuf:"bytes,4,opt,name=origin_key,json=originKey,proto3" json:"origin_key,omitempty"`
	Finalizer     bool                   `protobuf:"varint,5,opt,name=finalizer,proto3" json:"finalizer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MacroInfo) Reset() {
	*x = MacroInfo{}
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MacroInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MacroInfo) ProtoMessage() {}

func (x *MacroInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MacroInfo.ProtoReflect.Descriptor instead.
func (*MacroInfo) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_stardoc_output_proto_rawDescGZIP(), []int{2}
}

func (x *MacroInfo) GetMacroName() string {
	if x != nil {
		return x.MacroName
	}
	return ""
}

func (x *MacroInfo) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

func (x *MacroInfo) GetAttribute() []*AttributeInfo {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *MacroInfo) GetOriginKey() *OriginKey {
	if x != nil {
		return x.OriginKey
	}
	return nil
}

func (x *MacroInfo) GetFinalizer() bool {
	if x != nil {
		return x.Finalizer
	}
	return false
}

type AttributeInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Name              string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DocString         string                 `protobuf:"bytes,2,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	Type              AttributeType          `protobuf:"varint,3,opt,name=type,proto3,enum=stardoc_output.AttributeType" json:"type,omitempty"`
	Mandatory         bool                   `protobuf:"varint,4,opt,name=mandatory,proto3" json:"mandatory,omitempty"`
	ProviderNameGroup []*ProviderNameGroup   `protobuf:"bytes,5,rep,name=provider_name_group,json=providerNameGroup,proto3" json:"provider_name_group,omitempty"`
	DefaultValue      string                 `protobuf:"bytes,6,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Nonconfigurable   bool                   `protobuf:"varint,7,opt,name=nonconfigurable,proto3" json:"nonconfigurable,omitempty"`
	NativelyDefined   bool                   `protobuf:"varint,8,opt,name=natively_defined,json=nativelyDefined,proto3" json:"natively_defined,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AttributeInfo) Reset() {
	*x = AttributeInfo{}
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeInfo) ProtoMessage() {}

func (x *AttributeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeInfo.ProtoReflect.Descriptor instead.
func (*AttributeInfo) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_stardoc_output_proto_rawDescGZIP(), []int{3}
}

func (x *AttributeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttributeInfo) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

func (x *AttributeInfo) GetType() AttributeType {
	if x != nil {
		return x.Type
	}
	return AttributeType_UNKNOWN
}

func (x *AttributeInfo) GetMandatory() bool {
	if x != nil {
		return x.Mandatory
	}
	return false
}

func (x *AttributeInfo) GetProviderNameGroup() []*ProviderNameGroup {
	if x != nil {
		return x.ProviderNameGroup
	}
	return nil
}

func (x *AttributeInfo) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *AttributeInfo) GetNonconfigurable() bool {
	if x != nil {
		return x.Nonconfigurable
	}
	return false
}

func (x *AttributeInfo) GetNativelyDefined() bool {
	if x != nil {
		return x.NativelyDefined
	}
	return false
}

type ProviderNameGroup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  []string               `protobuf:"bytes,1,rep,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	OriginKey     []*OriginKey           `protobuf:"bytes,2,rep,name=origin_key,json=originKey,proto3" json:"origin_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderNameGroup) Reset() {
	*x = ProviderNameGroup{}
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderNameGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderNameGroup) ProtoMessage() {}

func (x *ProviderNameGroup) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderNameGroup.ProtoReflect.Descriptor instead.
func (*ProviderNameGroup) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_stardoc_output_proto_rawDescGZIP(), []int{4}
}

func (x *ProviderNameGroup) GetProviderName() []string {
	if x != nil {
		return x.ProviderName
	}
	return nil
}

func (x *ProviderNameGroup) GetOriginKey() []*OriginKey {
	if x != nil {
		return x.OriginKey
	}
	return nil
}

type StarlarkFunctionInfo struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	FunctionName  string                   `protobuf:"bytes,1,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	Parameter     []*FunctionParamInfo     `protobuf:"bytes,2,rep,name=parameter,proto3" json:"parameter,omitempty"`
	DocString     string                   `protobuf:"bytes,3,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	Return        *FunctionReturnInfo      `protobuf:"bytes,4,opt,name=return,proto3" json:"return,omitempty"`
	Deprecated    *FunctionDeprecationInfo `protobuf:"bytes,5,opt,name=deprecated,proto3" json:"deprecated,omitempty"`
	OriginKey     *OriginKey               `protobuf:"bytes,6,opt,name=origin_key,json=originKey,proto3" json:"origin_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StarlarkFunctionInfo) Reset() {
	*x = StarlarkFunctionInfo{}
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StarlarkFunctionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StarlarkFunctionInfo) ProtoMessage() {}

func (x *StarlarkFunctionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StarlarkFunctionInfo.ProtoReflect.Descriptor instead.
func (*StarlarkFunctionInfo) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_stardoc_output_proto_rawDescGZIP(), []int{5}
}

func (x *StarlarkFunctionInfo) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *StarlarkFunctionInfo) GetParameter() []*FunctionParamInfo {
	if x != nil {
		return x.Parameter
	}
	return nil
}

func (x *StarlarkFunctionInfo) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

func (x *StarlarkFunctionInfo) GetReturn() *FunctionReturnInfo {
	if x != nil {
		return x.Return
	}
	return nil
}

func (x *StarlarkFunctionInfo) GetDeprecated() *FunctionDeprecationInfo {
	if x != nil {
		return x.Deprecated
	}
	return nil
}

func (x *StarlarkFunctionInfo) GetOriginKey() *OriginKey {
	if x != nil {
		return x.OriginKey
	}
	return nil
}

type FunctionParamInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DocString     string                 `protobuf:"bytes,2,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	DefaultValue  string                 `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	Mandatory     bool                   `protobuf:"varint,4,opt,name=mandatory,proto3" json:"mandatory,omitempty"`
	Role          FunctionParamRole      `protobuf:"varint,5,opt,name=role,proto3,enum=stardoc_output.FunctionParamRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionParamInfo) Reset() {
	*x = FunctionParamInfo{}
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionParamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionParamInfo) ProtoMessage() {}

func (x *FunctionParamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionParamInfo.ProtoReflect.Descriptor instead.
func (*FunctionParamInfo) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_stardoc_output_proto_rawDescGZIP(), []int{6}
}

func (x *FunctionParamInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionParamInfo) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

func (x *FunctionParamInfo) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

func (x *FunctionParamInfo) GetMandatory() bool {
	if x != nil {
		return x.Mandatory
	}
	return false
}

func (x *FunctionParamInfo) GetRole() FunctionParamRole {
	if x != nil {
		return x.Role
	}
	return FunctionParamRole_PARAM_ROLE_UNSPECIFIED
}

type FunctionReturnInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocString     string                 `protobuf:"bytes,1,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionReturnInfo) Reset() {
	*x = FunctionReturnInfo{}
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionReturnInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionReturnInfo) ProtoMessage() {}

func (x *FunctionReturnInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionReturnInfo.ProtoReflect.Descriptor instead.
func (*FunctionReturnInfo) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_stardoc_output_proto_rawDescGZIP(), []int{7}
}

func (x *FunctionReturnInfo) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

type FunctionDeprecationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DocString     string                 `protobuf:"bytes,1,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionDeprecationInfo) Reset() {
	*x = FunctionDeprecationInfo{}
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionDeprecationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionDeprecationInfo) ProtoMessage() {}

func (x *FunctionDeprecationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionDeprecationInfo.ProtoReflect.Descriptor instead.
func (*FunctionDeprecationInfo) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_stardoc_output_proto_rawDescGZIP(), []int{8}
}

func (x *FunctionDeprecationInfo) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

type ProviderFieldInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	DocString     string                 `protobuf:"bytes,2,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderFieldInfo) Reset() {
	*x = ProviderFieldInfo{}
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderFieldInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderFieldInfo) ProtoMessage() {}

func (x *ProviderFieldInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderFieldInfo.ProtoReflect.Descriptor instead.
func (*ProviderFieldInfo) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_stardoc_output_proto_rawDescGZIP(), []int{9}
}

func (x *ProviderFieldInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProviderFieldInfo) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

type ProviderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	DocString     string                 `protobuf:"bytes,2,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	FieldInfo     []*ProviderFieldInfo   `protobuf:"bytes,3,rep,name=field_info,json=fieldInfo,proto3" json:"field_info,omitempty"`
	OriginKey     *OriginKey             `protobuf:"bytes,4,opt,name=origin_key,json=originKey,proto3" json:"origin_key,omitempty"`
	Init          *StarlarkFunctionInfo  `protobuf:"bytes,5,opt,name=init,proto3" json:"init,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProviderInfo) Reset() {
	*x = ProviderInfo{}
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProviderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProviderInfo) ProtoMessage() {}

func (x *ProviderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProviderInfo.ProtoReflect.Descriptor instead.
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_stardoc_output_proto_rawDescGZIP(), []int{10}
}

func (x *ProviderInfo) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ProviderInfo) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

func (x *ProviderInfo) GetFieldInfo() []*ProviderFieldInfo {
	if x != nil {
		return x.FieldInfo
	}
	return nil
}

func (x *ProviderInfo) GetOriginKey() *OriginKey {
	if x != nil {
		return x.OriginKey
	}
	return nil
}

func (x *ProviderInfo) GetInit() *StarlarkFunctionInfo {
	if x != nil {
		return x.Init
	}
	return nil
}

type AspectInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AspectName      string                 `protobuf:"bytes,1,opt,name=aspect_name,json=aspectName,proto3" json:"aspect_name,omitempty"`
	DocString       string                 `protobuf:"bytes,2,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	AspectAttribute []string               `protobuf:"bytes,3,rep,name=aspect_attribute,json=aspectAttribute,proto3" json:"aspect_attribute,omitempty"`
	Attribute       []*AttributeInfo       `protobuf:"bytes,4,rep,name=attribute,proto3" json:"attribute,omitempty"`
	OriginKey       *OriginKey             `protobuf:"bytes,5,opt,name=origin_key,json=originKey,proto3" json:"origin_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AspectInfo) Reset() {
	*x = AspectInfo{}
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AspectInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AspectInfo) ProtoMessage() {}

func (x *AspectInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AspectInfo.ProtoReflect.Descriptor instead.
func (*AspectInfo) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_stardoc_output_proto_rawDescGZIP(), []int{11}
}

func (x *AspectInfo) GetAspectName() string {
	if x != nil {
		return x.AspectName
	}
	return ""
}

func (x *AspectInfo) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

func (x *AspectInfo) GetAspectAttribute() []string {
	if x != nil {
		return x.AspectAttribute
	}
	return nil
}

func (x *AspectInfo) GetAttribute() []*AttributeInfo {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *AspectInfo) GetOriginKey() *OriginKey {
	if x != nil {
		return x.OriginKey
	}
	return nil
}

type ModuleExtensionInfo struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	ExtensionName string                         `protobuf:"bytes,1,opt,name=extension_name,json=extensionName,proto3" json:"extension_name,omitempty"`
	DocString     string                         `protobuf:"bytes,2,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	TagClass      []*ModuleExtensionTagClassInfo `protobuf:"bytes,3,rep,name=tag_class,json=tagClass,proto3" json:"tag_class,omitempty"`
	OriginKey     *OriginKey                     `protobuf:"bytes,4,opt,name=origin_key,json=originKey,proto3" json:"origin_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleExtensionInfo) Reset() {
	*x = ModuleExtensionInfo{}
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleExtensionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleExtensionInfo) ProtoMessage() {}

func (x *ModuleExtensionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleExtensionInfo.ProtoReflect.Descriptor instead.
func (*ModuleExtensionInfo) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_stardoc_output_proto_rawDescGZIP(), []int{12}
}

func (x *ModuleExtensionInfo) GetExtensionName() string {
	if x != nil {
		return x.ExtensionName
	}
	return ""
}

func (x *ModuleExtensionInfo) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

func (x *ModuleExtensionInfo) GetTagClass() []*ModuleExtensionTagClassInfo {
	if x != nil {
		return x.TagClass
	}
	return nil
}

func (x *ModuleExtensionInfo) GetOriginKey() *OriginKey {
	if x != nil {
		return x.OriginKey
	}
	return nil
}

type ModuleExtensionTagClassInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TagName       string                 `protobuf:"bytes,1,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	DocString     string                 `protobuf:"bytes,2,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	Attribute     []*AttributeInfo       `protobuf:"bytes,3,rep,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleExtensionTagClassInfo) Reset() {
	*x = ModuleExtensionTagClassInfo{}
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleExtensionTagClassInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleExtensionTagClassInfo) ProtoMessage() {}

func (x *ModuleExtensionTagClassInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleExtensionTagClassInfo.ProtoReflect.Descriptor instead.
func (*ModuleExtensionTagClassInfo) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_stardoc_output_proto_rawDescGZIP(), []int{13}
}

func (x *ModuleExtensionTagClassInfo) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *ModuleExtensionTagClassInfo) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

func (x *ModuleExtensionTagClassInfo) GetAttribute() []*AttributeInfo {
	if x != nil {
		return x.Attribute
	}
	return nil
}

type RepositoryRuleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleName      string                 `protobuf:"bytes,1,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	DocString     string                 `protobuf:"bytes,2,opt,name=doc_string,json=docString,proto3" json:"doc_string,omitempty"`
	Attribute     []*AttributeInfo       `protobuf:"bytes,3,rep,name=attribute,proto3" json:"attribute,omitempty"`
	Environ       []string               `protobuf:"bytes,4,rep,name=environ,proto3" json:"environ,omitempty"`
	OriginKey     *OriginKey             `protobuf:"bytes,5,opt,name=origin_key,json=originKey,proto3" json:"origin_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepositoryRuleInfo) Reset() {
	*x = RepositoryRuleInfo{}
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositoryRuleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositoryRuleInfo) ProtoMessage() {}

func (x *RepositoryRuleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositoryRuleInfo.ProtoReflect.Descriptor instead.
func (*RepositoryRuleInfo) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_stardoc_output_proto_rawDescGZIP(), []int{14}
}

func (x *RepositoryRuleInfo) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *RepositoryRuleInfo) GetDocString() string {
	if x != nil {
		return x.DocString
	}
	return ""
}

func (x *RepositoryRuleInfo) GetAttribute() []*AttributeInfo {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *RepositoryRuleInfo) GetEnviron() []string {
	if x != nil {
		return x.Environ
	}
	return nil
}

func (x *RepositoryRuleInfo) GetOriginKey() *OriginKey {
	if x != nil {
		return x.OriginKey
	}
	return nil
}

type OriginKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	File          string                 `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OriginKey) Reset() {
	*x = OriginKey{}
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OriginKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginKey) ProtoMessage() {}

func (x *OriginKey) ProtoReflect() protoreflect.Message {
	mi := &file_src_main_protobuf_stardoc_output_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OriginKey.ProtoReflect.Descriptor instead.
func (*OriginKey) Descriptor() ([]byte, []int) {
	return file_src_main_protobuf_stardoc_output_proto_rawDescGZIP(), []int{15}
}

func (x *OriginKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OriginKey) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

var File_src_main_protobuf_stardoc_output_proto protoreflect.FileDescriptor

const file_src_main_protobuf_stardoc_output_proto_rawDesc = "" +
	"\n" +
	"&src/main/protobuf/stardoc_output.proto\x12\x0estardoc_output\"\xae\x04\n" +
	"\n" +
	"ModuleInfo\x125\n" +
	"\trule_info\x18\x01 \x03(\v2\x18.stardoc_output.RuleInfoR\bruleInfo\x12A\n" +
	"\rprovider_info\x18\x02 \x03(\v2\x1c.stardoc_output.ProviderInfoR\fproviderInfo\x12A\n" +
	"\tfunc_info\x18\x03 \x03(\v2$.stardoc_output.StarlarkFunctionInfoR\bfuncInfo\x12;\n" +
	"\vaspect_info\x18\x04 \x03(\v2\x1a.stardoc_output.AspectInfoR\n" +
	"aspectInfo\x12)\n" +
	"\x10module_docstring\x18\x05 \x01(\tR\x0fmoduleDocstring\x12\x12\n" +
	"\x04file\x18\x06 \x01(\tR\x04file\x12W\n" +
	"\x15module_extension_info\x18\a \x03(\v2#.stardoc_output.ModuleExtensionInfoR\x13moduleExtensionInfo\x12T\n" +
	"\x14repository_rule_info\x18\b \x03(\v2\".stardoc_output.RepositoryRuleInfoR\x12repositoryRuleInfo\x128\n" +
	"\n" +
	"macro_info\x18\t \x03(\v2\x19.stardoc_output.MacroInfoR\tmacroInfo\"\xc7\x02\n" +
	"\bRuleInfo\x12\x1b\n" +
	"\trule_name\x18\x01 \x01(\tR\bruleName\x12\x1d\n" +
	"\n" +
	"doc_string\x18\x02 \x01(\tR\tdocString\x12;\n" +
	"\tattribute\x18\x03 \x03(\v2\x1d.stardoc_output.AttributeInfoR\tattribute\x128\n" +
	"\n" +
	"origin_key\x18\x04 \x01(\v2\x19.stardoc_output.OriginKeyR\toriginKey\x12T\n" +
	"\x14advertised_providers\x18\x05 \x01(\v2!.stardoc_output.ProviderNameGroupR\x13advertisedProviders\x12\x12\n" +
	"\x04test\x18\x06 \x01(\bR\x04test\x12\x1e\n" +
	"\n" +
	"executable\x18\a \x01(\bR\n" +
	"executable\"\xde\x01\n" +
	"\tMacroInfo\x12\x1d\n" +
	"\n" +
	"macro_name\x18\x01 \x01(\tR\tmacroName\x12\x1d\n" +
	"\n" +
	"doc_string\x18\x02 \x01(\tR\tdocString\x12;\n" +
	"\tattribute\x18\x03 \x03(\v2\x1d.stardoc_output.AttributeInfoR\tattribute\x128\n" +
	"\n" +
	"origin_key\x18\x04 \x01(\v2\x19.stardoc_output.OriginKeyR\toriginKey\x12\x1c\n" +
	"\tfinalizer\x18\x05 \x01(\bR\tfinalizer\"\xe0\x02\n" +
	"\rAttributeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"doc_string\x18\x02 \x01(\tR\tdocString\x121\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1d.stardoc_output.AttributeTypeR\x04type\x12\x1c\n" +
	"\tmandatory\x18\x04 \x01(\bR\tmandatory\x12Q\n" +
	"\x13provider_name_group\x18\x05 \x03(\v2!.stardoc_output.ProviderNameGroupR\x11providerNameGroup\x12#\n" +
	"\rdefault_value\x18\x06 \x01(\tR\fdefaultValue\x12(\n" +
	"\x0fnonconfigurable\x18\a \x01(\bR\x0fnonconfigurable\x12)\n" +
	"\x10natively_defined\x18\b \x01(\bR\x0fnativelyDefined\"r\n" +
	"\x11ProviderNameGroup\x12#\n" +
	"\rprovider_name\x18\x01 \x03(\tR\fproviderName\x128\n" +
	"\n" +
	"origin_key\x18\x02 \x03(\v2\x19.stardoc_output.OriginKeyR\toriginKey\"\xda\x02\n" +
	"\x14StarlarkFunctionInfo\x12#\n" +
	"\rfunction_name\x18\x01 \x01(\tR\ffunctionName\x12?\n" +
	"\tparameter\x18\x02 \x03(\v2!.stardoc_output.FunctionParamInfoR\tparameter\x12\x1d\n" +
	"\n" +
	"doc_string\x18\x03 \x01(\tR\tdocString\x12:\n" +
	"\x06return\x18\x04 \x01(\v2\".stardoc_output.FunctionReturnInfoR\x06return\x12G\n" +
	"\n" +
	"deprecated\x18\x05 \x01(\v2'.stardoc_output.FunctionDeprecationInfoR\n" +
	"deprecated\x128\n" +
	"\n" +
	"origin_key\x18\x06 \x01(\v2\x19.stardoc_output.OriginKeyR\toriginKey\"\xc0\x01\n" +
	"\x11FunctionParamInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"doc_string\x18\x02 \x01(\tR\tdocString\x12#\n" +
	"\rdefault_value\x18\x03 \x01(\tR\fdefaultValue\x12\x1c\n" +
	"\tmandatory\x18\x04 \x01(\bR\tmandatory\x125\n" +
	"\x04role\x18\x05 \x01(\x0e2!.stardoc_output.FunctionParamRoleR\x04role\"3\n" +
	"\x12FunctionReturnInfo\x12\x1d\n" +
	"\n" +
	"doc_string\x18\x01 \x01(\tR\tdocString\"8\n" +
	"\x17FunctionDeprecationInfo\x12\x1d\n" +
	"\n" +
	"doc_string\x18\x01 \x01(\tR\tdocString\"F\n" +
	"\x11ProviderFieldInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"doc_string\x18\x02 \x01(\tR\tdocString\"\x88\x02\n" +
	"\fProviderInfo\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x1d\n" +
	"\n" +
	"doc_string\x18\x02 \x01(\tR\tdocString\x12@\n" +
	"\n" +
	"field_info\x18\x03 \x03(\v2!.stardoc_output.ProviderFieldInfoR\tfieldInfo\x128\n" +
	"\n" +
	"origin_key\x18\x04 \x01(\v2\x19.stardoc_output.OriginKeyR\toriginKey\x128\n" +
	"\x04init\x18\x05 \x01(\v2$.stardoc_output.StarlarkFunctionInfoR\x04init\"\xee\x01\n" +
	"\n" +
	"AspectInfo\x12\x1f\n" +
	"\vaspect_name\x18\x01 \x01(\tR\n" +
	"aspectName\x12\x1d\n" +
	"\n" +
	"doc_string\x18\x02 \x01(\tR\tdocString\x12)\n" +
	"\x10aspect_attribute\x18\x03 \x03(\tR\x0faspectAttribute\x12;\n" +
	"\tattribute\x18\x04 \x03(\v2\x1d.stardoc_output.AttributeInfoR\tattribute\x128\n" +
	"\n" +
	"origin_key\x18\x05 \x01(\v2\x19.stardoc_output.OriginKeyR\toriginKey\"\xdf\x01\n" +
	"\x13ModuleExtensionInfo\x12%\n" +
	"\x0eextension_name\x18\x01 \x01(\tR\rextensionName\x12\x1d\n" +
	"\n" +
	"doc_string\x18\x02 \x01(\tR\tdocString\x12H\n" +
	"\ttag_class\x18\x03 \x03(\v2+.stardoc_output.ModuleExtensionTagClassInfoR\btagClass\x128\n" +
	"\n" +
	"origin_key\x18\x04 \x01(\v2\x19.stardoc_output.OriginKeyR\toriginKey\"\x94\x01\n" +
	"\x1bModuleExtensionTagClassInfo\x12\x19\n" +
	"\btag_name\x18\x01 \x01(\tR\atagName\x12\x1d\n" +
	"\n" +
	"doc_string\x18\x02 \x01(\tR\tdocString\x12;\n" +
	"\tattribute\x18\x03 \x03(\v2\x1d.stardoc_output.AttributeInfoR\tattribute\"\xe1\x01\n" +
	"\x12RepositoryRuleInfo\x12\x1b\n" +
	"\trule_name\x18\x01 \x01(\tR\bruleName\x12\x1d\n" +
	"\n" +
	"doc_string\x18\x02 \x01(\tR\tdocString\x12;\n" +
	"\tattribute\x18\x03 \x03(\v2\x1d.stardoc_output.AttributeInfoR\tattribute\x12\x18\n" +
	"\aenviron\x18\x04 \x03(\tR\aenviron\x128\n" +
	"\n" +
	"origin_key\x18\x05 \x01(\v2\x19.stardoc_output.OriginKeyR\toriginKey\"3\n" +
	"\tOriginKey\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04file\x18\x02 \x01(\tR\x04file*\xf3\x01\n" +
	"\rAttributeType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\b\n" +
	"\x04NAME\x10\x01\x12\a\n" +
	"\x03INT\x10\x02\x12\t\n" +
	"\x05LABEL\x10\x03\x12\n" +
	"\n" +
	"\x06STRING\x10\x04\x12\x0f\n" +
	"\vSTRING_LIST\x10\x05\x12\f\n" +
	"\bINT_LIST\x10\x06\x12\x0e\n" +
	"\n" +
	"LABEL_LIST\x10\a\x12\v\n" +
	"\aBOOLEAN\x10\b\x12\x15\n" +
	"\x11LABEL_STRING_DICT\x10\t\x12\x0f\n" +
	"\vSTRING_DICT\x10\n" +
	"\x12\x14\n" +
	"\x10STRING_LIST_DICT\x10\v\x12\n" +
	"\n" +
	"\x06OUTPUT\x10\f\x12\x0f\n" +
	"\vOUTPUT_LIST\x10\r\x12\x14\n" +
	"\x10LABEL_DICT_UNARY\x10\x0e*\xb4\x01\n" +
	"\x11FunctionParamRole\x12\x1a\n" +
	"\x16PARAM_ROLE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PARAM_ROLE_ORDINARY\x10\x01\x12\x1e\n" +
	"\x1aPARAM_ROLE_POSITIONAL_ONLY\x10\x02\x12\x1b\n" +
	"\x17PARAM_ROLE_KEYWORD_ONLY\x10\x03\x12\x16\n" +
	"\x12PARAM_ROLE_VARARGS\x10\x04\x12\x15\n" +
	"\x11PARAM_ROLE_KWARGS\x10\x05BG\n" +
	"0com.google.devtools.build.lib.starlarkdocextractB\x13StardocOutputProtosb\x06proto3"

var (
	file_src_main_protobuf_stardoc_output_proto_rawDescOnce sync.Once
	file_src_main_protobuf_stardoc_output_proto_rawDescData []byte
)

func file_src_main_protobuf_stardoc_output_proto_rawDescGZIP() []byte {
	file_src_main_protobuf_stardoc_output_proto_rawDescOnce.Do(func() {
		file_src_main_protobuf_stardoc_output_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_main_protobuf_stardoc_output_proto_rawDesc), len(file_src_main_protobuf_stardoc_output_proto_rawDesc)))
	})
	return file_src_main_protobuf_stardoc_output_proto_rawDescData
}

var file_src_main_protobuf_stardoc_output_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_src_main_protobuf_stardoc_output_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_src_main_protobuf_stardoc_output_proto_goTypes = []any{
	(AttributeType)(0),                  // 0: stardoc_output.AttributeType
	(FunctionParamRole)(0),              // 1: stardoc_output.FunctionParamRole
	(*ModuleInfo)(nil),                  // 2: stardoc_output.ModuleInfo
	(*RuleInfo)(nil),                    // 3: stardoc_output.RuleInfo
	(*MacroInfo)(nil),                   // 4: stardoc_output.MacroInfo
	(*AttributeInfo)(nil),               // 5: stardoc_output.AttributeInfo
	(*ProviderNameGroup)(nil),           // 6: stardoc_output.ProviderNameGroup
	(*StarlarkFunctionInfo)(nil),        // 7: stardoc_output.StarlarkFunctionInfo
	(*FunctionParamInfo)(nil),           // 8: stardoc_output.FunctionParamInfo
	(*FunctionReturnInfo)(nil),          // 9: stardoc_output.FunctionReturnInfo
	(*FunctionDeprecationInfo)(nil),     // 10: stardoc_output.FunctionDeprecationInfo
	(*ProviderFieldInfo)(nil),           // 11: stardoc_output.ProviderFieldInfo
	(*ProviderInfo)(nil),                // 12: stardoc_output.ProviderInfo
	(*AspectInfo)(nil),                  // 13: stardoc_output.AspectInfo
	(*ModuleExtensionInfo)(nil),         // 14: stardoc_output.ModuleExtensionInfo
	(*ModuleExtensionTagClassInfo)(nil), // 15: stardoc_output.ModuleExtensionTagClassInfo
	(*RepositoryRuleInfo)(nil),          // 16: stardoc_output.RepositoryRuleInfo
	(*OriginKey)(nil),                   // 17: stardoc_output.OriginKey
}
var file_src_main_protobuf_stardoc_output_proto_depIdxs = []int32{
	3,  // 0: stardoc_output.ModuleInfo.rule_info:type_name -> stardoc_output.RuleInfo
	12, // 1: stardoc_output.ModuleInfo.provider_info:type_name -> stardoc_output.ProviderInfo
	7,  // 2: stardoc_output.ModuleInfo.func_info:type_name -> stardoc_output.StarlarkFunctionInfo
	13, // 3: stardoc_output.ModuleInfo.aspect_info:type_name -> stardoc_output.AspectInfo
	14, // 4: stardoc_output.ModuleInfo.module_extension_info:type_name -> stardoc_output.ModuleExtensionInfo
	16, // 5: stardoc_output.ModuleInfo.repository_rule_info:type_name -> stardoc_output.RepositoryRuleInfo
	4,  // 6: stardoc_output.ModuleInfo.macro_info:type_name -> stardoc_output.MacroInfo
	5,  // 7: stardoc_output.RuleInfo.attribute:type_name -> stardoc_output.AttributeInfo
	17, // 8: stardoc_output.RuleInfo.origin_key:type_name -> stardoc_output.OriginKey
	6,  // 9: stardoc_output.RuleInfo.advertised_providers:type_name -> stardoc_output.ProviderNameGroup
	5,  // 10: stardoc_output.MacroInfo.attribute:type_name -> stardoc_output.AttributeInfo
	17, // 11: stardoc_output.MacroInfo.origin_key:type_name -> stardoc_output.OriginKey
	0,  // 12: stardoc_output.AttributeInfo.type:type_name -> stardoc_output.AttributeType
	6,  // 13: stardoc_output.AttributeInfo.provider_name_group:type_name -> stardoc_output.ProviderNameGroup
	17, // 14: stardoc_output.ProviderNameGroup.origin_key:type_name -> stardoc_output.OriginKey
	8,  // 15: stardoc_output.StarlarkFunctionInfo.parameter:type_name -> stardoc_output.FunctionParamInfo
	9,  // 16: stardoc_output.StarlarkFunctionInfo.return:type_name -> stardoc_output.FunctionReturnInfo
	10, // 17: stardoc_output.StarlarkFunctionInfo.deprecated:type_name -> stardoc_output.FunctionDeprecationInfo
	17, // 18: stardoc_output.StarlarkFunctionInfo.origin_key:type_name -> stardoc_output.OriginKey
	1,  // 19: stardoc_output.FunctionParamInfo.role:type_name -> stardoc_output.FunctionParamRole
	11, // 20: stardoc_output.ProviderInfo.field_info:type_name -> stardoc_output.ProviderFieldInfo
	17, // 21: stardoc_output.ProviderInfo.origin_key:type_name -> stardoc_output.OriginKey
	7,  // 22: stardoc_output.ProviderInfo.init:type_name -> stardoc_output.StarlarkFunctionInfo
	5,  // 23: stardoc_output.AspectInfo.attribute:type_name -> stardoc_output.AttributeInfo
	17, // 24: stardoc_output.AspectInfo.origin_key:type_name -> stardoc_output.OriginKey
	15, // 25: stardoc_output.ModuleExtensionInfo.tag_class:type_name -> stardoc_output.ModuleExtensionTagClassInfo
	17, // 26: stardoc_output.ModuleExtensionInfo.origin_key:type_name -> stardoc_output.OriginKey
	5,  // 27: stardoc_output.ModuleExtensionTagClassInfo.attribute:type_name -> stardoc_output.AttributeInfo
	5,  // 28: stardoc_output.RepositoryRuleInfo.attribute:type_name -> stardoc_output.AttributeInfo
	17, // 29: stardoc_output.RepositoryRuleInfo.origin_key:type_name -> stardoc_output.OriginKey
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_src_main_protobuf_stardoc_output_proto_init() }
func file_src_main_protobuf_stardoc_output_proto_init() {
	if File_src_main_protobuf_stardoc_output_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_main_protobuf_stardoc_output_proto_rawDesc), len(file_src_main_protobuf_stardoc_output_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_main_protobuf_stardoc_output_proto_goTypes,
		DependencyIndexes: file_src_main_protobuf_stardoc_output_proto_depIdxs,
		EnumInfos:         file_src_main_protobuf_stardoc_output_proto_enumTypes,
		MessageInfos:      file_src_main_protobuf_stardoc_output_proto_msgTypes,
	}.Build()
	File_src_main_protobuf_stardoc_output_proto = out.File
	file_src_main_protobuf_stardoc_output_proto_goTypes = nil
	file_src_main_protobuf_stardoc_output_proto_depIdxs = nil
}
