load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "descriptorpb",
    srcs = ["descriptor.pb.go"],
    importpath = "github.com/stackb/bazel-aquery-differ/genproto/google.golang.org/protobuf/types/descriptorpb",
    visibility = ["//visibility:public"],
    deps = [
        "@org_golang_google_protobuf//reflect/protoreflect:go_default_library",
        "@org_golang_google_protobuf//runtime/protoimpl:go_default_library",
    ],
)
