load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "option_filters",
    srcs = ["option_filters.pb.go"],
    importpath = "github.com/stackb/bazel-aquery-differ/genproto/github.com/bazelbuild/bazelapis/src/main/protobuf/option_filters",
    visibility = ["//visibility:public"],
    deps = [
        "@org_golang_google_protobuf//reflect/protoreflect:go_default_library",
        "@org_golang_google_protobuf//runtime/protoimpl:go_default_library",
    ],
)
