load("//rules:defs.bzl", "aquery_diff", "aquery_git_diff")

aquery_git_diff(
    name = "git_diff",
    after = "77bac585176f97d3f482a702db3e1155900fbacd",
    before = "a771ee789340aa3164d86491728828afeb5973cb",
    target = "deps(//cmd/aquerydiff)",
)

aquery_diff(
    name = "diff",
    after = "after.pbtext",
    before = "before.pbtext",
    target = "deps(//cmd/aquerydiff)",
)
